<?php

namespace App\Traits;

use Illuminate\Http\Request;

trait ValidationTrait
{
    private function validateHoSo(Request $request, $id = null)
    {
        return $request->validate([
            'HoDem' => 'required|string|max:255',
            'Ten' => 'required|string|max:255',
            'NgayThangNamSinh' => 'required|date_format:Y-m-d|after:1900-01-01',
            'GioiTinh' => 'required|in:Nam,Nữ',
            'DanToc' => 'required',
            'CCCD' => 'required|size:12|unique:tb_hoso,CCCD,' .$id. '',
            'Email' => 'required|regex:/^[a-zA-Z][a-zA-Z0-9]*(\.?[a-z0-9]){5,}@gmail\.com$/
            |unique:tb_hoso,Email,' .$id. '',
            'SDT' => 'required|regex:/^0[1-9][0-9]{8}$/|unique:tb_hoso,SDT,' .$id.'',
            'MaTinh' => 'required',
            'MaQuanHuyen' => 'required',
            'MaTinhTruong' => 'required',
            'MaQuanHuyenTruong' => 'required',
            'TenTruong' => 'required|string|max:255',
            'MaPhuongXa' => 'required',
            'DiaChi' => 'required|string|max:255',
            'DoiTuongUT' => 'nullable',
            'KhuVucUT' => 'required',
            'NamTotNghiep'  => 'required|numeric|after_or_equal:' . (date('Y') - 10),
            'HinhThuc' => 'required|string|max:255',
            'DiemMon1' => 'required|numeric|between:0,10',
            'DiemMon2' => 'required|numeric|between:0,10',
            'DiemMon3' => 'required|numeric|between:0,10',
            'Nganh_ID' => 'required',
            'TrangThai' => 'in:1,0|nullable',
            'BangKQ12.*' => 'nullable|file|mimes:jpeg,png,jpg,gif|max:5120',
            'HocBaBia' => 'nullable|file|mimes:jpeg,png,jpg,gif|max:5120',
            'ChungNhanTN' => 'nullable|file|mimes:jpeg,png,jpg,gif|max:5120',
            'ChungNhanUT' => 'nullable|file|mimes:jpeg,png,jpg,gif|max:5120',
        ], [
            'unique' => ':attribute đã được đăng ký',
            'size' => ':attribute sai kích thước',
            'required' => 'Yêu cầu bắt buộc!',
            'string' => ':attribute không hợp lệ!',
            'max' => ':attribute vượt quá giới hạn',
            'min' => ':attribute thấp hơn giới hạn',
            'date_format' => ':attribute không hợp lệ!',
            'in' => ':attribute không thuộc giá trị trên',
            'numeric' => ':attribute phải thuộc kiểu số',
            'after_or_equal' => ':attribute nằm ngoài khoảng cho phép!',
            'email' => ':attribute không hợp lệ!',
            'SDT.regex' => ':attribute không đúng định dạng (10 số, không bao gồm kí tự đặc biệt)',
            'Email.regex' => ':attribute không đúng định dạng (abc..@gmail.com)',
            'between' => ':attribute phải nằm trong khoảng từ 0-10',
            'after' => ':attribute phải sau ngày 1 tháng 1 năm 1900.',
            'file' => ':attribute phải là hình ảnh.',
            'mimes' => ':attribute phải là định dạng jpeg, png, jpg, hoặc gif.',
        ], [
            'HoDem' => 'Họ đệm',
            'Ten' => 'Tên',
            'NgayThangNamSinh' => 'Ngày tháng năm sinh',
            'GioiTinh' => 'Giới tính',
            'DanToc' => 'Dân tộc',
            'CCCD' => 'CCCD',
            'Email' => 'Email',
            'SDT' => 'Số điện thoại',
            'MaTinh' => 'Mã tỉnh',
            'MaQuanHuyen' => 'Mã quận huyện',
            'MaTinhTruong' => 'Mã tỉnh trường',
            'MaQuanHuyenTruong' => 'Mã quận huyện trường',
            'TenTruong' => 'Tên trường',
            'MaPhuongXa' => 'Mã phường xã',
            'DiaChi' => 'Địa chỉ',
            'DoiTuongUT' => 'Đối tượng ưu tiên',
            'KhuVucUT' => 'Khu vực ưu tiên',
            'NamTotNghiep'  => 'Năm tốt nghiệp',
            'HinhThuc' => 'Hình thức',
            'DiemMon1' => 'Điểm môn 1',
            'DiemMon2' => 'Điểm môn 2',
            'DiemMon3' => 'Điểm môn 3',
            'Nganh_ID' => 'Ngành ID',
            'TrangThai' => 'Trạng thái',
            'BangKQ12' => 'Bảng kết quả 12',
            'HocBaBia' => 'Học bạ bìa',
            'ChungNhanTN' => 'Chứng nhận tốt nghiệp',
            'ChungNhanUT' => 'Chứng nhận ưu tiên',
        ]);
    }
}
